### ISSUE TITLE
Push it to AtmosphereJS

### ISSUE THREAD

**Issue by Tolsi** [raix/Meteor-localforage#1]
Why not make a new Meteor package?

**Comment by raix** [comment]
I dont think this package is working - it was a test for the ground:db - I ended up writing ground:store - at the moment its only utilizing localstorage - I guess I ended up not caring about the storage but simply just getting the best storage available (ground:store will be able to enable cordova storage etc.)

**Comment by raix** [comment]
+ground:store created namespaced storage + events - so thats an improvement needed by ground:db

**Comment by Tolsi** [comment]
I installed this package locally, I connect it to the project and it just works.
I saw the ground:store, but I don't want to use it yet (localstorage is slow in my opinion).
I think this package can be added to the atmosphere.js for a change, everyone will choose what he wants.

**Comment by Tolsi** [comment]
I tested this package on Android browsers and it works. But in iOS's Safari there were problems with it, I was moved to ground:store. Thanks you for your work!
