### ISSUE TITLE
More recent localforage?

### ISSUE THREAD

**Issue by jaskinn** [raix/Meteor-localforage#4]
Is it possible to update to a more recent localforage?

**Comment by raix** [comment]
I'll dig deeper into this next week

**Comment by derwaldgeist** [comment]
+1

I was pointed to this package today and think it's quite interesting. But I am a bit hesitating as it hasn't been maintained for 2 years. Are you planning to support this?

I also looked into ground:db, but for my use-case, I would need a device-specific storage that should not be synced to the server, so localForage seems to fit better.

**Comment by raix** [comment]
https://github.com/raix/Meteor-localforage/tree/ES2015 (1.2.4-rc.3)

https://github.com/raix/Meteor-localforage-sqlite (should work on cordova)

https://github.com/GroundMeteor/db/tree/es2015-localforage

**Comment by sahanDissanayake** [comment]
@raix difference between Meteor-localforage and GroundDB ?

**Comment by raix** [comment]
I'm deprecating these packages in favor of using meteor 1.3 and using Mozillas official npm localforage package

**Comment by raix** [comment]
(the new ground db uses localforage directly from npm)
